const abilities = [
    "Overgrow",
    "Blaze",
    "Torrent",
    "Shield Dust",
    "Shed Skin",
    "Compoundeyes",
    "Swarm",
    "Keen Eye",
    "Run Away",
    "Intimidate",
    "Static",
    "Sand Veil",
    "Poison Point",
    "Cute Charm",
    "Flash Fire",
    "Inner Focus",
    "Chlorophyll",
    "Effect Spore",
    "Pickup",
    "Limber",
    "Damp",
    "Vital Spirit",
    "Water Absorb",
    "Synchronize",
    "Guts",
    "Clear Body",
    "Rock Head",
    "Oblivious",
    "Magnet Pull",
    "Thick Fat",
    "Stench",
    "Shell Armor",
    "Levitate",
    "Cursed Body",
    "Insomnia",
    "Hyper Cutter",
    "Soundproof",
    "Own Tempo",
    "Lightningrod",
    "Natural Cure",
    "Early Bird",
    "Swift Swim",
    "Illuminate",
    "Flame Body",
    "Volt Absorb",
    "Trace",
    "Immunity",
    "Pressure",
    "Hustle",
    "Sturdy",
    "Speed Boost",
    "Shadow Tag",
    "Serene Grace",
    "Magma Armor",
    "Suction Cups",
    "Sand Stream",
    "Truant",
    "Wonder Guard",
    "Pure Power",
    "Plus",
    "Minus",
    "Liquid Ooze",
    "Rough Skin",
    "Water Veil",
    "White Smoke",
    "Battle Armor",
    "Marvel Scale",
    "Forecast",
    "Color Change",
    "Drizzle",
    "Drought",
    "Air Lock",
    "Simple",
    "Rivalry",
    "Mold Breaker",
    "Anticipation",
    "Honey Gather",
    "Flower Gift",
    "Sticky Hold",
    "Technician",
    "Aftermath",
    "Steadfast",
    "Snow Warning",
    "Motor Drive",
    "Leaf Guard",
    "Snow Cloak",
    "Adaptability",
    "Slow Start",
    "Hydration",
    "Bad Dreams",
    "Multitype",
    "Victory Star",
    "Gluttony",
    "Forewarn",
    "Big Pecks",
    "Unaware",
    "Sand Rush",
    "Healer",
    "Prankster",
    "Reckless",
    "Sheer Force",
    "Wonder Skin ",
    "Mummy",
    "Solid Rock",
    "Defeatist",
    "Illusion",
    "Frisk",
    "Overcoat",
    "Ice Body",
    "Iron Barbs",
    "Telepathy",
    "Iron Fist",
    "Defiant",
    "Justified",
    "Turboblaze",
    "Teravolt",
    "Sand Force",
    "Download",
    "Flower Veil",
    "Sap Sipper",
    "Fur Coat",
    "No Guard",
    "Stance Change",
    "Sweet Veil",
    "Contrary",
    "Tough Claws",
    "Mega Launcher",
    "Dry Skin",
    "Strong Jaw",
    "Refrigerate",
    "Cheek Pouch",
    "Fairy Aura",
    "Dark Aura",
    "Aura Break",
    "Magician",
    "Stakeout",
    "Battery",
    "Dancer",
    "Schooling",
    "Merciless",
    "Water Bubble",
    "Corrosion",
    "Fluffy",
    "Receiver",
    "Wimp Out",
    "Emergency Exit",
    "Water Compaction",
    "Innards Out",
    "RKS System",
    "Shields Down",
    "Comatose",
    "Disguise",
    "Dazzling",
    "Berserk",
    "Steelworker",
    "Bulletproof",
    "Electric Surge",
    "Psychic Surge",
    "Grassy Surge",
    "Misty Surge",
    "Full Metal Body",
    "Shadow Shield",
    "Beast Boost",
    "Prism Armor",
    "Soul-Heart",
    "Chlorophyll",
    "Solar Power",
    "Rain Dish",
    "Run Away",
    "Tinted Lens",
    "Sniper",
    "Tangled Feet",
    "Guts",
    "Shed Skin",
    "Lightningrod",
    "Sand Rush",
    "Rivalry",
    "Magic Guard",
    "Drought",
    "Competitive",
    "Infiltrator",
    "Stench",
    "Effect Spore",
    "Dry Skin",
    "Arena Trap",
    "Technician",
    "Cloud Nine",
    "Anger Point",
    "Flash Fire",
    "Damp",
    "Inner Focus",
    "No Guard",
    "Gluttony",
    "Liquid Ooze",
    "Sturdy",
    "Own Tempo",
    "Early Bird",
    "Hydration",
    "Sticky Hold",
    "Skill Link",
    "Forewarn",
    "Shell Armor",
    "Static",
    "Harvest",
    "Reckless",
    "Iron Fist",
    "Oblivious",
    "Rock Head",
    "Serene Grace",
    "Leaf Guard",
    "Scrappy",
    "Water Veil",
    "Natural Cure",
    "Filter",
    "Vital Spirit",
    "Mold Breaker",
    "Rattled",
    "Moxie",
    "Imposter",
    "Adaptability",
    "Quick Feet",
    "Download",
    "Battle Armor",
    "Pressure",
    "Thick Fat",
    "Snow Cloak",
    "Flame Body",
    "Marvel Scale",
    "Multiscale",
    "Unnerve",
    "Sheer Force",
    "Keen Eye",
    "Insomnia",
    "Illuminate",
    "Plus",
    "Healer",
    "Huge Power",
    "Pickup",
    "Compoundeyes",
    "Water Absorb",
    "Magic Bounce",
    "Super Luck",
    "Telepathy",
    "Overcoat",
    "Sand Veil",
    "Swift Swim",
    "Hustle",
    "Frisk",
    "Steadfast",
    "Regenerator",
    "Unburden",
    "Speed Boost",
    "Drizzle",
    "Trace",
    "Poison Heal",
    "Magnet Pull",
    "Normalize",
    "Stall",
    "Intimidate",
    "Volt Absorb",
    "Swarm",
    "Poison Point",
    "Simple",
    "Solid Rock",
    "Toxic Boost",
    "Anticipation",
    "Storm Drain",
    "Protean",
    "Ice Body",
    "Light Metal",
    "Defiant",
    "Unaware",
    "Soundproof",
    "Klutz",
    "Aftermath",
    "Heatproof",
    "Rough Skin",
    "Sand Force",
    "Pickpocket",
    "Justified",
    "Cursed Body",
    "Contrary",
    "Overgrow",
    "Blaze",
    "Torrent",
    "Synchronize",
    "Motor Drive",
    "Weak Armor",
    "Sand Stream",
    "Poison Touch",
    "Zen Mode",
    "Big Pecks",
    "Snow Warning",
    "Sap Sipper",
    "Minus",
    "Slush Rush",
    "Limber",
    "Teravolt",
    "Bulletproof",
    "Magician",
    "Cheek Pouch",
    "Gale Wings",
    "Friend Guard",
    "Symbiosis",
    "Grass Pelt",
    "Aroma Veil",
    "Suction Cups",
    "Pixilate",
    "Power Construct",
    "Long Reach",
    "Liquid Voice",
    "Strong Jaw",
    "Shield Dust",
    "Stamina",
    "Queenly Majesty",
    "Triage",
    "Surge Surfer",
    "Wonder Skin ",
    "Analytic",
    "Prankster",
    "Immunity",
    "Honey Gather",
    "Moody",
    "Heavy Metal",
    "Cute Charm",
    "Flare Boost",
    "Levitate",
    "Shadow Tag",
    "Clear Body",
    "White Smoke",
    "Truant",
    "Turboblaze",
    "Battle Bond",
    "Gooey",
    "Sweet Veil",
    "Fur Coat",
    "Tangling Hair",
    "Galvanize",
    "Power of Alchemy"
    ];
const generation = [1,2,3,4,5,6,7]; 
const type = [
    "Grass",
    "Fire",
    "Water",
    "Bug",
    "Normal",
    "Poison",
    "Electric",
    "Ground",
    "Fairy",
    "Fighting",
    "Psychic",
    "Rock",
    "Ghost",
    "Ice",
    "Dragon",
    "Dark",
    "Steel",
    "Flying"
];
exports.abilities = abilities;
exports.generation = generation;
exports.type = type;